language: c
compiler:
- gcc
before_install:
- git tag v1.0.0-travis
- echo "deb http://us.archive.ubuntu.com/ubuntu/ vivid main universe restricted multiverse" | sudo tee -a /etc/apt/sources.list
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -y -qq libnl-genl-3-dev libnl-3-dev libtool autoconf2.13 git libpcre3 pkg-config libpcre3-dev libprotobuf-dev protobuf-compiler tcpdump libcunit1-dev libcppunit-dev libncurses5-dev bc 1> /dev/null
- sudo apt-get remove gcc-4.6 1> /dev/null
install:
- cp linux/config-TRAVIS linux/.config
env:
#- FLAGS=
script:
- cd linux
- sudo make -j 5 bzImage modules
- sudo make -j 5 modules_install
- sudo make install
- sudo make headers_install
- cd ..
- sed --e 's/--enable-java-bindings//g' install-user-from-scratch > install-user-from-scratch
- sudo ./install-user-from-scratch /usr/local/irati
notifications:
email:
- irati-ci@freelists.org